version: 2
build:
  os: "ubuntu-22.04"
  tools:
    nodejs: "18"
    # You can also specify other tool versions:
    # python: "3"
  commands:
      # "docs/" was created following the Docusaurus tutorial:
      # npx create-docusaurus@latest docs classic
      #
      # Install Docusaurus dependencies
      - npm install
      # Build the site
      - npm run build
      # Copy generated files into Read the Docs directory
      - mkdir --parents $READTHEDOCS_OUTPUT/html/
      - cp --recursive docs/build/* $READTHEDOCS_OUTPUT/html/
