version: 2
build:
  os: "ubuntu-22.04"
  tools:
    nodejs: "14"
    # You can also specify other tool versions:
    # python: "3"
  commands:
      # "docs/" was created following the Docusaurus tutorial:
      # npx create-docusaurus@latest docs classic
      #
      # Install Docusaurus dependencies
      - npm install -g npm@6.14.12
      - npm install -g gitbook-cli@2.3.2
      - npm install yarn@1.22.21
      - yarn install 
      - yarn build
      # Copy generated files into Read the Docs directory
      - mkdir --parents $READTHEDOCS_OUTPUT/html/
      - cp --recursive build/* $READTHEDOCS_OUTPUT/html/
